/**
 * Autonomous Marketing Email System
 * Sends personalized, event-triggered emails to merchants.
 * 
 * CRITICAL: Does NOT touch Shopify OAuth, webhooks, billing, or sync systems.
 * Triggered by: scheduled runs or explicit action payloads.
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const ADMIN_EMAIL = 'rohan.a.roberts@gmail.com';
const FROM_NAME = 'ProfitShield AI';

// Email templates
const TEMPLATES = {
  onboarding_day1: (tenant) => ({
    subject: `🚀 Welcome to ProfitShield — Let's protect your profits`,
    body: `Hi there,

Welcome to ProfitShield AI! We're excited to help you protect and grow your store profits.

Here's how to get the most out of ProfitShield in your first 24 hours:

✅ STEP 1: Connect Your Shopify Store
Go to Settings > Integrations and connect your Shopify store to start syncing orders automatically.

✅ STEP 2: Review Your Profit Dashboard
Once connected, your AI dashboard will show your real profit margin, risk scores, and profit leaks.

✅ STEP 3: Set Up Alert Rules
Visit Alerts > Rules to configure notifications for low-margin orders, high-risk fraud signals, and shipping losses.

🎯 Your 14-day free trial gives you full access to all Pro features.

Need help? Just reply to this email or open the Help chat inside ProfitShield.

— The ProfitShield AI Team
support@profitshield.ai`
  }),

  integration_reminder: (tenant) => ({
    subject: `⚡ Your ProfitShield store isn't connected yet`,
    body: `Hi,

We noticed your ProfitShield account is set up but your store isn't connected yet.

You're missing out on:
• Real-time profit tracking on every order
• AI fraud detection saving you from chargebacks
• Automatic shipping loss detection
• Margin leak forensics

It only takes 2 minutes to connect your Shopify store.

→ Log in and click "Connect Store" to get started.

If you need help, reply to this email and our team will assist you immediately.

— ProfitShield AI
support@profitshield.ai`
  }),

  profit_opportunity: (tenant, data) => ({
    subject: `💡 AI found a profit opportunity in your store`,
    body: `Hi,

ProfitShield's AI has analyzed your recent orders and found something important:

${data.insight || 'We detected potential profit improvements in your store.'}

${data.estimated_value ? `Estimated opportunity: $${data.estimated_value.toLocaleString()}/month` : ''}

To act on this insight:
1. Log in to ProfitShield
2. Visit Dashboard > AI Insights
3. Review the detailed breakdown

This opportunity was identified by analyzing your order margin patterns, shipping costs, and risk exposure.

— ProfitShield AI
support@profitshield.ai`
  }),

  trial_ending: (tenant) => ({
    subject: `⏰ Your ProfitShield trial ends soon`,
    body: `Hi,

Your ProfitShield free trial ends in 3 days.

During your trial, ProfitShield has been protecting your profits with:
✅ AI fraud detection
✅ Real-time margin tracking
✅ Profit leak detection
✅ Risk score monitoring

To continue protecting your profits, upgrade to a paid plan before your trial ends.

→ Visit Billing in your dashboard to choose a plan.

Questions? Reply to this email and we'll help you find the right plan.

— ProfitShield AI
support@profitshield.ai`
  }),

  risk_alert: (tenant, data) => ({
    subject: `🚨 High-risk order detected on your store`,
    body: `Hi,

ProfitShield AI detected a high-risk order on your store that needs your attention.

Order Details:
• Order: ${data.order_number || 'N/A'}
• Risk Score: ${data.risk_score || 'High'}
• Risk Reason: ${data.risk_reason || 'Multiple fraud signals detected'}

Recommended Action: ${data.recommended_action || 'Review this order before fulfilling'}

→ Log in to ProfitShield > Orders to review and take action.

This alert was automatically generated by ProfitShield's AI risk engine.

— ProfitShield AI
support@profitshield.ai`
  })
};

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const body = await req.json().catch(() => ({}));
  const action = body.action || 'run_scheduled';
  const results = { sent: 0, skipped: 0, failed: 0, emails: [] };

  try {
    // Scheduled run: send event-triggered emails to all tenants
    if (action === 'run_scheduled') {
      const tenants = await base44.asServiceRole.entities.Tenant.list('-created_date', 100);

      for (const tenant of tenants) {
        if (!tenant.billing_email && !tenant.shop_domain) continue;
        const email = tenant.billing_email || null;
        if (!email) { results.skipped++; continue; }

        try {
          // Onboarding: send day-1 email if tenant was created in last 24h and hasn't gotten one
          const ageHours = (Date.now() - new Date(tenant.created_date).getTime()) / 3600000;
          
          if (ageHours <= 26 && !tenant.onboarding_email_sent) {
            const tpl = TEMPLATES.onboarding_day1(tenant);
            await base44.asServiceRole.integrations.Core.SendEmail({ to: email, from_name: FROM_NAME, ...tpl });
            await base44.asServiceRole.entities.Tenant.update(tenant.id, { onboarding_email_sent: true });
            results.sent++;
            results.emails.push({ type: 'onboarding_day1', to: email, tenant: tenant.id });
            continue;
          }

          // Integration reminder: store connected but no integration after 3 days
          if (ageHours > 72 && ageHours < 96 && !tenant.onboarding_completed && !tenant.integration_reminder_sent) {
            const tpl = TEMPLATES.integration_reminder(tenant);
            await base44.asServiceRole.integrations.Core.SendEmail({ to: email, from_name: FROM_NAME, ...tpl });
            await base44.asServiceRole.entities.Tenant.update(tenant.id, { integration_reminder_sent: true });
            results.sent++;
            results.emails.push({ type: 'integration_reminder', to: email, tenant: tenant.id });
            continue;
          }

          // Trial ending: send 3 days before trial_ends_at
          if (tenant.trial_ends_at && tenant.plan_status === 'trial') {
            const trialEndMs = new Date(tenant.trial_ends_at).getTime();
            const daysLeft = (trialEndMs - Date.now()) / (1000 * 60 * 60 * 24);
            if (daysLeft > 2.5 && daysLeft < 3.5 && !tenant.trial_ending_email_sent) {
              const tpl = TEMPLATES.trial_ending(tenant);
              await base44.asServiceRole.integrations.Core.SendEmail({ to: email, from_name: FROM_NAME, ...tpl });
              await base44.asServiceRole.entities.Tenant.update(tenant.id, { trial_ending_email_sent: true });
              results.sent++;
              results.emails.push({ type: 'trial_ending', to: email, tenant: tenant.id });
            }
          }

        } catch (e) {
          results.failed++;
          console.error(`[MarketingEmail] Failed for tenant ${tenant.id}: ${e.message}`);
        }
      }
    }

    // Manual: send a specific email type to a specific tenant
    if (action === 'send_manual') {
      const { tenant_id, email_type, to_email, data: emailData } = body;
      if (!to_email || !email_type || !TEMPLATES[email_type]) {
        return Response.json({ success: false, error: 'Missing to_email or invalid email_type' }, { status: 400 });
      }
      const tenant = tenant_id ? await base44.asServiceRole.entities.Tenant.filter({ id: tenant_id }).then(r => r[0]) : {};
      const tpl = TEMPLATES[email_type](tenant || {}, emailData || {});
      await base44.asServiceRole.integrations.Core.SendEmail({ to: to_email, from_name: FROM_NAME, ...tpl });
      results.sent++;
      results.emails.push({ type: email_type, to: to_email });
    }

    // Send admin summary
    if (results.sent > 0) {
      await base44.asServiceRole.integrations.Core.SendEmail({
        to: ADMIN_EMAIL,
        from_name: 'ProfitShield Email Engine',
        subject: `📧 Marketing Email Summary — ${results.sent} sent`,
        body: `Autonomous Marketing Email Engine Report\n\nSent: ${results.sent}\nSkipped: ${results.skipped}\nFailed: ${results.failed}\n\nEmails:\n${results.emails.map(e => `• ${e.type} → ${e.to}`).join('\n')}`
      });
    }

    console.log(`[MarketingEmail] Done — sent=${results.sent} skipped=${results.skipped} failed=${results.failed}`);
    return Response.json({ success: true, action, ...results });

  } catch (error) {
    console.error('[MarketingEmail] Fatal:', error.message);
    return Response.json({ success: false, error: error.message }, { status: 500 });
  }
});